spring:
  application:
    name: gestion_stock_api

  config:
    import: optional:file:api/.env[.properties]

  sql:
    init:
      mode: always


  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true